version: 2.1
jobs:
  build:
    parameters:
      deploy:
        type: boolean
        default: false
    docker:
      - image: docker:18

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Cloning source
          command: git clone https://github.com/posthop/backend.git build

      - run:
          name: Building Docker image
          command: docker build -t posthop-backend:latest .

      - when:
          condition: << parameters.deploy >>
          steps:
            - run:
                name: Set up Docker
                command: echo TODO

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          deploy: false
          filters:
            branches:
              only: master

  build_and_deploy:
    jobs:
      - build:
          deploy: true
          filters:
            tags:
              only: /.*/
