version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Installing git
          command: sudo apt-get update && sudo apt-get install -y git

      - run:
          name: Cloning source
          command: git clone https://github.com/posthop/backend.git build

      - run:
          name: Building Docker image
          command: docker build -t posthop-backend:latest .
      - run:
          name: Saving image 
          command: docker save -o image.tar posthop-backend
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  deploy:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "deb http://packages.cloud.google.com/apt cloud-sdk-stretch main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      - run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install google-cloud-sdk

      - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

      - run: gcloud auth configure-docker

      - setup_remote_docker

      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar

      - run: docker tag posthop-backend:latest gcr.io/${GOOGLE_PROJECT_ID}/posthop-backend:latest
      - run: export DOCKER_SHA=$(docker images posthop-backend:latest -q --no-trunc)
      - run: docker push gcr.io/${GOOGLE_PROJECT_ID}/posthop-backend:latest
      - run: sudo apt-get install kubectl
      - run: gcloud container clusters get-credentials api-cluster
      - run: kubectl set image deployment posthop-api posthop-api=gcr.io/cuhacking19/posthop-backend:${DOCKER_SHA}

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master

  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.+/
            branches:
                ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.+/
            branches:
                ignore: /.*/
