version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Installing git
          command: sudo apt-get update && sudo apt-get install -y git

      - run:
          name: Cloning source
          command: git clone https://github.com/posthop/backend.git build

      - run:
          name: Building Docker image
          command: docker build -t posthop-backend:latest .
  deploy:
    docker:
      - image: remie/circleci-docker-gcloud
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

      - run: gcloud auth configure-docker

      - run: docker push gcr.io/${GOOGLE_PROJECT_ID}/posthop-backend:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master

  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.+/
            branches:
                ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.+/
            branches:
                ignore: /.*/
